-- =========================================================
-- Employee Payroll Management Database
-- Course: CPS510
-- Description: Core database schema for payroll management
-- =========================================================

-- ===== Housekeeping =====
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE leave_request CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE payroll CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE salary CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE employee CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE department CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

-- ===== Department =====
CREATE TABLE department (
  dept_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dept_name VARCHAR2(100) NOT NULL UNIQUE,
  dept_manager_id NUMBER,
  dept_email VARCHAR2(120),
  dept_phone_number VARCHAR2(20),
  dept_creation_date DATE,
  dept_hierarchy_lvl NUMBER,
  dept_status VARCHAR2(15) DEFAULT 'Active',
  CONSTRAINT chk_dept_status CHECK (dept_status IN ('Active','Inactive'))
);

-- ===== Employee =====
CREATE TABLE employee (
  emp_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dept_id NUMBER NOT NULL,
  emp_number VARCHAR2(20) UNIQUE,
  emp_name VARCHAR2(120) NOT NULL,
  gender VARCHAR2(20),
  pronoun VARCHAR2(20),
  date_of_birth DATE,
  marital_status VARCHAR2(20),
  phone_number VARCHAR2(25),
  email VARCHAR2(120) UNIQUE,
  address VARCHAR2(200),
  position_title VARCHAR2(80),
  bank_account_no VARCHAR2(34),
  emp_username VARCHAR2(60) UNIQUE,
  emp_password_hash VARCHAR2(128),
  emp_status VARCHAR2(15) DEFAULT 'Active',
  emp_emergency_contact VARCHAR2(120),
  hire_date DATE DEFAULT SYSDATE,
  CONSTRAINT chk_emp_status CHECK (emp_status IN ('Active','Inactive','OnLeave')),
  CONSTRAINT fk_emp_dept FOREIGN KEY (dept_id)
    REFERENCES department(dept_id)
);

-- Department manager reference
ALTER TABLE department
ADD CONSTRAINT fk_dept_manager
FOREIGN KEY (dept_manager_id)
REFERENCES employee(emp_id);

-- ===== Salary =====
CREATE TABLE salary (
  sal_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  emp_id NUMBER NOT NULL,
  dept_id NUMBER NOT NULL,
  sal_amount NUMBER(12,2) NOT NULL,
  bonus NUMBER(12,2) DEFAULT 0,
  vacation_pay NUMBER(12,2) DEFAULT 0,
  gross_total NUMBER(12,2),
  effective_from DATE DEFAULT SYSDATE,
  effective_to DATE,
  CONSTRAINT fk_sal_emp FOREIGN KEY (emp_id) REFERENCES employee(emp_id),
  CONSTRAINT fk_sal_dept FOREIGN KEY (dept_id) REFERENCES department(dept_id),
  CONSTRAINT chk_salary_dates
    CHECK (effective_to IS NULL OR effective_to >= effective_from)
);

-- ===== Payroll =====
CREATE TABLE payroll (
  transaction_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  emp_id NUMBER NOT NULL,
  sal_id NUMBER NOT NULL,
  dept_id NUMBER NOT NULL,
  gross_total NUMBER(12,2) NOT NULL,
  bank_account_no VARCHAR2(34),
  date_of_issue DATE DEFAULT SYSDATE,
  payroll_report VARCHAR2(2000),
  CONSTRAINT fk_pay_emp FOREIGN KEY (emp_id) REFERENCES employee(emp_id),
  CONSTRAINT fk_pay_sal FOREIGN KEY (sal_id) REFERENCES salary(sal_id),
  CONSTRAINT fk_pay_dept FOREIGN KEY (dept_id) REFERENCES department(dept_id)
);

-- ===== Leave Request =====
CREATE TABLE leave_request (
  leave_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  emp_id NUMBER NOT NULL,
  leave_type VARCHAR2(30) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  reason VARCHAR2(200),
  status VARCHAR2(15) DEFAULT 'Pending',
  CONSTRAINT chk_leave_status
    CHECK (status IN ('Pending','Approved','Rejected','Cancelled')),
  CONSTRAINT chk_leave_dates CHECK (end_date >= start_date),
  CONSTRAINT fk_leave_emp FOREIGN KEY (emp_id)
    REFERENCES employee(emp_id)
);
